# Generated by Django 4.1.5 on 2023-01-23 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('joind_date', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(choices=[('0', 'student'), ('1', 'advisor'), ('2', 'supervisor'), ('3', 'head of department'), ('4', 'karshenas'), ('5', 'finished')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Thesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=512)),
                ('state', models.CharField(choices=[('0', 'student'), ('1', 'advisor'), ('2', 'supervisor'), ('3', 'head of department'), ('4', 'karshenas'), ('5', 'finished')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advisor', to='mainApp.user')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='mainApp.user')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor', to='mainApp.user')),
            ],
        ),
    ]
