# Generated by Django 4.1.5 on 2023-01-23 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='state',
        ),
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('0', 'student'), ('1', 'professor'), ('2', 'karshenas'), ('3', 'head')], default=0, max_length=1),
            preserve_default=False,
        ),
    ]
