# Generated by Django 4.1.5 on 2023-01-23 00:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_remove_user_state_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='pdf_file',
            field=models.FileField(default=0, upload_to='thesises/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
            preserve_default=False,
        ),
    ]
