# Generated by Django 4.1.5 on 2023-01-23 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_user_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='type',
            new_name='user_type',
        ),
    ]
